services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    profiles: ["db", "full"]
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-metabase-db.sh:/docker-entrypoint-initdb.d/init-metabase-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mooveit-network

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    profiles: ["app", "full"]
    # No depends_on for the app profile when deployed on VM2
    environment:
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT:-8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080/api}
      - GIN_MODE=${GIN_MODE:-release}
      - AT_API_KEY=${AT_API_KEY:-atsk_75abb9d3046c9b32b8761828b1e398082421cbabe0f7dd9ea2bc37e7b254ad14876702f9}
      - AT_USERNAME=${AT_USERNAME:-MooveIt_KE}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-ojtx esuf bizk slbh}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - EMAIL_FROM=${EMAIL_FROM:-mooveitlimited@gmail.com}
      - JWT_SECRET=${JWT_SECRET:-w1yN8qcCFc0cLx5fjb/7Se3DH839c67h53cBndor5Mc=}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - mooveit-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    profiles: ["metabase", "full"]
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: ${DB_PORT:-5432}
      MB_DB_USER: ${DB_USER}
      MB_DB_PASS: ${DB_PASSWORD}
      MB_DB_HOST: ${DB_HOST:-postgres}
      JAVA_TIMEZONE: Africa/Nairobi
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      MB_ENCRYPTION_SECRET_KEY: ${MB_ENCRYPTION_SECRET_KEY:-UqHJzl1rBN3FSL2p4keudxY5DI7KaGMm}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 2m
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data
    networks:
      - mooveit-network

networks:
  mooveit-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
  metabase_data:
