
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: mesongoisaac
      POSTGRES_PASSWORD: 789012
      POSTGRES_DB: Mooveit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # go-app:
  #   build: .
  #   container_name: go-app
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: mesongoisaac
  #     DB_PASSWORD: 789012
  #     DB_NAME: Mooveit
  #   ports:
  #     - "8080:8080"
  #   command: ["go", "run", "main.go"]

volumes:
  postgres_data:
