services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    profiles: ["app", "redis", "full"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    restart: always
    profiles: ["app", "full"]
    depends_on:
      - redis
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - PORT=${PORT:-8080}
      - BASE_URL=${BASE_URL}
      - GIN_MODE=${GIN_MODE:-release}
      - AT_API_KEY=${AT_API_KEY}
      - AT_USERNAME=${AT_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - uploads_data:/app/uploads

volumes:
  redis_data:
  uploads_data:
